default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  # 以下、3行追加
  username: user
  host: localhost

development:
  <<: *default
  database: sss_development
test:
  <<: *default
  database: sss_test
