default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: masayukisuzuki
  host: localhost

development:
  <<: *default
  database: sss_development
test:
  <<: *default
  database: sss_test<%= ENV['TEST_ENV_NUMBER'] %>
